# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Local Linux

stages:
- stage: Build
  displayName: CI - Build Stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - script: |
        echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
        echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_11_X64)/bin:$(PATH)"
      displayName: "Set Java Version"
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'BuildArtifact'

- stage: Deploy
  displayName: CD - Deploy Stage
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
    - job: Deploy_App_On_VM
      displayName: Deploy App on VM
      steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'specific'
            downloadPath: '$(System.ArtifactsDirectory)'
        - script: |
            scp -i ~/Documents/java-vm-key.pem $(System.ArtifactsDirectory)/TestArtifact/target/api-rest-project-0.0.1-SNAPSHOT.war azureuser@20.226.10.251:/opt/tomcat/webapps
        
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Testing Service Connection'
            appType: 'webAppLinux'
            WebAppName: 'java-webapp-test'
            packageForLinux: '$(System.ArtifactsDirectory)/TestArtifact/target/*.war'
            RuntimeStack: 'JAVA|11-java11'